### PR TITLE
[TEMPLATE]: "Fix" caching mechanism in workflow

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks. Clearly this line came from an earlier project with manual CI setup. I’d be curious to know what was the motivation. Maybe @utensil or @zeramorphic knows about this?

**Comment by utensil** [comment]
[Related Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/doc-gen.20not.20finding.20Mathlib.20declarations/near/473219659).

**Comment by pitmonticone** [comment]
I didn't investigate enough to have any clear idea about what is actually going on here. 

The "reasoning" behind it was "Ok, let's see what happens if we save a little bit more to cache". 

It can very well be completely spurious.

**Comment by pitmonticone** [comment]
I think this is not a fix. I'm going to close this PR.

**Pull request closed without merging**
