### PR TITLE
fix workflow issues and typos in console.printed messages

### PR DESCRIPTION
**Pull request by pitmonticone**
Fix workflow issues discussed [here](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/leanblueprint.20command.20line.20tool) and a few typos in console.printed messages.

### CODE REVIEW

**Comment by RemyDegenne** [comment]
If -R is indeed needed everywhere the -Kenv option is used, could you also add an -R to the commands in the "get cache" and "build project" step?

**Comment by pitmonticone** [comment]
@RemyDegenne Sure, I'll do it later today. Thanks for your comment.

**Comment by RemyDegenne** [comment]
I have an alternative proposal for CI here: #17

**Comment by pitmonticone** [comment]
@RemyDegenne Done

**Comment by PatrickMassot** [comment]
Thanks!

**Pull request merged**
